parser: '@typescript-eslint/parser'
parserOptions:
  project:
    - ".eslint.tsconfig.json"
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
rules:
  arrow-body-style: off
  prefer-arrow-callback: warn
  no-underscore-dangle: off
  # '@typescipt-eslint/interface-name-prefix': ['error', 'always']
  # '@typescript-eslint/no-floating-promises': warn
  '@typescript-eslint/no-unused-vars': warn
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/indent': 'off'
